### ISSUE TITLE
Tidy operation marks all messages parsed as read

### ISSUE THREAD

**Issue by bchazalet** [sapristi/mail_juicer#6]
First, thanks for the tool, it's going to be very useful to me!

When I run the tidy operation like this:
```bash
mmuxer tidy --config-file config.yaml --folder INBOX
```

it does move the messages I expected to be moved but it also marks all parsed messages in the folder as read. Is there a way to avoid that and just leave untouched the rest of the messages?

the rule I'm using:
```
rules:
  - move_to: INBOX/QUARANTAINE
    condition:
      ANY:
        - FROM: someguy@hostname.com
```
